### ISSUE TITLE
How should configure the annotation named `mellanox.infiniband.app`

### ISSUE THREAD

**Issue by shilingna** [Mellanox/ib-kubernetes#98]
It is the test pod as follows
```
apiVersion: v1
kind: Pod
metadata:
  name: sriov-ib
  namespace: ib
  annotations:
    k8s.v1.cni.cncf.io/networks: ib@ib
    mellanox.infiniband.app: ib
spec:
  nodeName: sg-dcu002.hogpu.cc
  containers:
    - name: cni
      image: hub.hobot.cc/k8snetworkplumbingwg/mellanox/rping-test
      imagePullPolicy: IfNotPresent
      command:
        - sleep
        - 3600s
      resources:
        requests:
          mellanox.com/sriov_ib_rdma: '1'
        limits:
          mellanox.com/sriov_ib_rdma: '1'
```
 But I got some error
 ```
 infiniBand SRIOV-CNI failed, InfiniBand status "mellanox.infiniband.app" is not "configured" please check mellanox ib-kubernetes
 ```
 what should I do ? anyone help me, thanks.
